In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor

In [2]:
data=pd.read_csv('Car_Model.csv',na_values=['?'])

In [3]:
data.isna().sum()

mpg             0
Cylinders       0
displacement    0
Horsepower      6
Weight          0
accelaration    0
ModelYear       0
Version         0
Carname         0
dtype: int64

In [4]:
data.describe(include='all')

mpg   Cylinders  displacement  Horsepower       Weight  \
count   398.000000  398.000000    398.000000  392.000000   398.000000   
unique         NaN         NaN           NaN         NaN          NaN   
top            NaN         NaN           NaN         NaN          NaN   
freq           NaN         NaN           NaN         NaN          NaN   
mean     23.514573    5.454774    193.425879  104.469388  2970.424623   
std       7.815984    1.701004    104.269838   38.491160   846.841774   
min       9.000000    3.000000     68.000000   46.000000  1613.000000   
25%      17.500000    4.000000    104.250000   75.000000  2223.750000   
50%      23.000000    4.000000    148.500000   93.500000  2803.500000   
75%      29.000000    8.000000    262.000000  126.000000  3608.000000   
max      46.600000    8.000000    455.000000  230.000000  5140.000000   

        accelaration   ModelYear     Version     Carname  
count     398.000000  398.000000  398.000000         398  
unique           NaN         NaN         NaN         305  
top              NaN         NaN         NaN  ford pinto  
freq             NaN         NaN         NaN           6  
mean       15.568090   76.010050    1.572864         NaN  
std         2.757689    3.697627    0.802055         NaN  
min         8.000000   70.000000    1.000000         NaN  
25%        13.825000   73.000000    1.000000         NaN  
50%        15.500000   76.000000    1.000000         NaN  
75%        17.175000   79.000000    2.000000         NaN  
max        24.800000   82.000000    3.000000         NaN

In [7]:
data['Horsepower'][30:40]

30     90.000000
31     95.000000
32    104.469388
33    100.000000
34    105.000000
35    100.000000
36     88.000000
37    100.000000
38    165.000000
39    175.000000
Name: Horsepower, dtype: float64

In [29]:
data.describe(include='all')

mpg   Cylinders  displacement  Horsepower       Weight  \
count   398.000000  398.000000    398.000000  392.000000   398.000000   
unique         NaN         NaN           NaN         NaN          NaN   
top            NaN         NaN           NaN         NaN          NaN   
freq           NaN         NaN           NaN         NaN          NaN   
mean     23.514573    5.454774    193.425879  104.469388  2970.424623   
std       7.815984    1.701004    104.269838   38.491160   846.841774   
min       9.000000    3.000000     68.000000   46.000000  1613.000000   
25%      17.500000    4.000000    104.250000   75.000000  2223.750000   
50%      23.000000    4.000000    148.500000   93.500000  2803.500000   
75%      29.000000    8.000000    262.000000  126.000000  3608.000000   
max      46.600000    8.000000    455.000000  230.000000  5140.000000   

        accelaration   ModelYear     Version     Carname  
count     398.000000  398.000000  398.000000         398  
unique           NaN         NaN         NaN         305  
top              NaN         NaN         NaN  ford pinto  
freq             NaN         NaN         NaN           6  
mean       15.568090   76.010050    1.572864         NaN  
std         2.757689    3.697627    0.802055         NaN  
min         8.000000   70.000000    1.000000         NaN  
25%        13.825000   73.000000    1.000000         NaN  
50%        15.500000   76.000000    1.000000         NaN  
75%        17.175000   79.000000    2.000000         NaN  
max        24.800000   82.000000    3.000000         NaN

In [6]:
data["Horsepower"].fillna(data["Horsepower"].mean(),inplace=True)

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
mpg             398 non-null float64
Cylinders       398 non-null int64
displacement    398 non-null float64
Horsepower      398 non-null int64
Weight          398 non-null int64
accelaration    398 non-null float64
ModelYear       398 non-null int64
Version         398 non-null int64
Carname         398 non-null object
dtypes: float64(3), int64(5), object(1)
memory usage: 28.1+ KB


In [34]:
data['Horsepower']=data['Horsepower'].apply(np.int64)

In [8]:
X=data[['Weight','displacement','Horsepower','ModelYear','Version','accelaration','Cylinders']]
Y=data['mpg']

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=100)
from sklearn.preprocessing import StandardScaler
scaled_X_train=StandardScaler().fit_transform(X_train)

In [10]:
model = RandomForestRegressor(n_estimators=100, oob_score=True)
model.fit(scaled_X_train, Y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=100,
                      n_jobs=None, oob_score=True, random_state=None, verbose=0,
                      warm_start=False)

In [11]:
model.oob_score_

0.8644283036206426

In [89]:
model.feature_importances_

array([0.25420782, 0.32904288, 0.06873876, 0.14183937, 0.00696625,
       0.03030972, 0.16889521])

In [12]:
pd.Series(model.feature_importances_,index=X_train.columns)

Weight          0.246597
displacement    0.336630
Horsepower      0.071948
ModelYear       0.137952
Version         0.006636
accelaration    0.029654
Cylinders       0.170583
dtype: float64

In [91]:
X=data[['Weight','displacement','Horsepower','ModelYear','accelaration','Cylinders']]
Y=data['mpg']
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=100)
from sklearn.preprocessing import StandardScaler
scaled_X_train=StandardScaler().fit_transform(X_train)
model = RandomForestRegressor(n_estimators=100, oob_score=True)
model.fit(scaled_X_train, Y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=100,
                      n_jobs=None, oob_score=True, random_state=None, verbose=0,
                      warm_start=False)

In [92]:
model.feature_importances_

array([0.25077296, 0.39273236, 0.0740499 , 0.13691884, 0.03036305,
       0.11516289])

In [93]:
model.oob_score_

0.8623181260305895

In [94]:
pd.Series(model.feature_importances_,index=X_train.columns)

Weight          0.250773
displacement    0.392732
Horsepower      0.074050
ModelYear       0.136919
accelaration    0.030363
Cylinders       0.115163
dtype: float64

In [95]:
X=data[['Weight','displacement','Horsepower','ModelYear','Cylinders']]
Y=data['mpg']
from sklearn.preprocessing import StandardScaler
scaled_X_train=StandardScaler().fit_transform(X)
model = RandomForestRegressor(n_estimators=100, oob_score=True, random_state=42)
model.fit(scaled_X_train, Y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=100,
                      n_jobs=None, oob_score=True, random_state=42, verbose=0,
                      warm_start=False)

In [96]:
model.oob_score_

0.8684110848936577

In [13]:
X=data[['Weight','displacement','Horsepower','ModelYear','Version','accelaration','Cylinders']]
Y=data['mpg']
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=100)
from sklearn.preprocessing import StandardScaler
scaled_X_train=StandardScaler().fit_transform(X_train)
model = RandomForestRegressor(n_estimators=100, oob_score=True)
model.fit(scaled_X_train, Y_train)
model.oob_score_

0.8626139881238316

In [14]:
%%timeit
model = RandomForestRegressor(1000, oob_score=True, n_jobs=1)
model.fit(scaled_X_train,Y_train)

2.03 s ± 5.69 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [15]:
%%timeit
model = RandomForestRegressor(1000, oob_score=True, n_jobs=-1)
model.fit(scaled_X_train,Y_train)

1.39 s ± 45 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [16]:
n_estimator_options = [50, 100, 200, 500, 1000, 2000,3000]

for trees in n_estimator_options:
    model = RandomForestRegressor(trees, oob_score=True, n_jobs=-1)
    model.fit(scaled_X_train,Y_train)
    print(trees, 'trees')
    s=model.oob_score_
    print('OOB: ', s)

50 trees
OOB:  0.8491231663999315
100 trees
OOB:  0.8692546367158531
200 trees
OOB:  0.8641788434582621
500 trees
OOB:  0.8641103758304489
1000 trees
OOB:  0.8667188506266013
2000 trees
OOB:  0.8653901833236659
3000 trees
OOB:  0.8667277831114184


In [17]:
max_features_options = ["auto", None, "sqrt", "log2", 0.9, 0.2,1]

for max_features in max_features_options:
    model = RandomForestRegressor(n_estimators=1000, oob_score=True, n_jobs=-1,max_features=max_features)
    model.fit(scaled_X_train,Y_train)
    print(max_features, "No_Of_features")
    s=model.oob_score_
    print('OOB: ', s)

auto No_Of_features
OOB:  0.867529000752608
None No_Of_features
OOB:  0.8652327782589306
sqrt No_Of_features
OOB:  0.8684064731730524
log2 No_Of_features
OOB:  0.8659992097760172
0.9 No_Of_features
OOB:  0.865687478788288
0.2 No_Of_features
OOB:  0.8649623655302738
1 No_Of_features
OOB:  0.8625133638044109


In [18]:
min_samples_leaf_options = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

for min_samples in min_samples_leaf_options:
    model = RandomForestRegressor(n_estimators=1000, oob_score=True, n_jobs=-1,max_features="sqrt", min_samples_leaf=min_samples)
    model.fit(scaled_X_train,Y_train)
    print(min_samples, "min samples")
    s=model.oob_score_
    print('OOB: ', s)

1 min samples
OOB:  0.8685062983019213
2 min samples
OOB:  0.8651586810864375
3 min samples
OOB:  0.8564034309668724
4 min samples
OOB:  0.8525175672794935
5 min samples
OOB:  0.8496626058763158
6 min samples
OOB:  0.845865810891709
7 min samples
OOB:  0.8433521246993976
8 min samples
OOB:  0.8412673128767341
9 min samples
OOB:  0.8384871658760418
10 min samples
OOB:  0.8333583519712867


In [19]:
model = RandomForestRegressor(n_estimators=1000, 
                              oob_score=True, 
                              n_jobs=-1, 
                              max_features="sqrt", 
                              min_samples_leaf=5)
model.fit(scaled_X_train,Y_train)
s=model.oob_score_
print('OOB: ', s)

OOB:  0.8500670641092309


In [22]:
scaler=StandardScaler()
scaled_X_train=scaler.fit_transform(X_train)
scaled_X_test=scaler.transform(X_test)
Y_pred=model.predict(scaled_X_test)
from sklearn import metrics
from sklearn.metrics import r2_score
print("MAE: ",metrics.mean_absolute_error(Y_test,Y_pred))
print("MSE: ",metrics.mean_squared_error(Y_test,Y_pred))
print("RMSE: ",np.sqrt(metrics.mean_squared_error(Y_test,Y_pred)))
print("R2_score: ",r2_score(Y_test,Y_pred))
r2_test=r2_score(Y_test,Y_pred)
print("AdjR2_score: ",1-(((1-r2_test)*(len(X_test)-1))/(len(X_test)-X_test.shape[1]-1)))

MAE:  1.7423473281133277
MSE:  5.778168191976866
RMSE:  2.4037820599997968
R2_score:  0.8967206324921613
AdjR2_score:  0.8866795828733436


In [24]:
Y_pred

array([34.596484  , 30.56483648, 23.01443078, 20.15038699, 29.74478713,
       23.17422693, 19.06389427, 24.51018172, 15.19604276, 25.57784689,
       21.28625715, 32.95503846, 19.35023045, 28.49581354, 29.32873739,
       18.6405365 , 16.0331954 , 26.29746596, 25.34690659, 19.9641137 ,
       30.93308889, 25.02395699, 32.734967  , 23.14184268, 17.220859  ,
       14.05365391, 22.13635018, 14.07285321, 27.0721699 , 13.71273119,
       35.97440717, 26.83305532, 17.45370675, 24.76528219, 24.33533828,
       19.95086646, 15.02150414, 29.86898205, 14.83762733, 14.30905568,
       13.49864045, 13.12775861, 17.04853903, 33.70870228, 17.15075953,
       20.68898463, 14.61147746, 15.04313972, 18.26416623, 32.37577947,
       27.00281299, 25.01089096, 33.83763202, 19.15310536, 19.05884313,
       15.7409163 , 25.88802831, 25.32031105, 13.24929071, 34.1895755 ,
       31.24179433, 21.17276632, 24.2925033 , 18.03447489, 36.05133309,
       17.68612444, 19.96010924, 17.74346019, 28.12877115, 14.12

In [25]:
Y_test

326    43.4
54     35.0
78     21.0
169    20.0
368    27.0
       ... 
266    30.0
69     12.0
239    30.0
46     22.0
50     28.0
Name: mpg, Length: 80, dtype: float64

In [ ]:
+